# Generated by Django 5.0.1 on 2024-02-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellPurchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='infomation_about_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lostItem',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/lostItems/'),
        ),
    ]
