# Generated by Django 5.0.1 on 2024-02-02 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SellPurchase', '0002_student_infomation_about_item_student_lostitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='item_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
