# Generated by Django 5.0.1 on 2024-02-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SellPurchase', '0003_student_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='infomation_about_item',
            new_name='information_about_item',
        ),
    ]
